Repository schemaspy/schemaspy, pull requests merged in 2018-05, with the labels that each got.

#302 Never use both SQL and DatabaseMetaData in DatabaseService.getBasicTableMeta
  src/main/java/org/schemaspy/service/DatabaseService.java
  src/test/java/org/schemaspy/testcontainer/MysqlSchemaLeakageIT.java
  src/test/resources/integrationTesting/mysql_schema_leakage/dbScripts/mysql_table_view_collision.sql
Labels: bug, bugfix

#323 Update mssql05.properties to include schema to prevent empty table comments
  src/main/resources/org/schemaspy/types/mssql05.properties
  src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java
  src/test/resources/integrationTesting/dbScripts/mssql.sql
Labels: bugfix

#332 Main.run doesn't call System.exit()
  src/main/java/org/schemaspy/Main.java
  src/main/java/org/schemaspy/SchemaSpyConfiguration.java
  src/main/java/org/schemaspy/cli/CommandLineArgumentParser.java
  src/main/java/org/schemaspy/cli/SchemaSpyRunner.java
  src/test/java/org/schemaspy/MainTest.java
  src/test/java/org/schemaspy/cli/CommandLineArgumentParserTest.java
  src/test/java/org/schemaspy/cli/SchemaSpyRunnerTest.java
  src/test/java/org/schemaspy/integrationtesting/StackTraceLoggingIT.java
  src/test/java/org/schemaspy/integrationtesting/mysql/MysqlHTMLIT.java
  src/test/java/org/schemaspy/integrationtesting/mysql/MysqlKeyWordTableIT.java
  src/test/java/org/schemaspy/integrationtesting/mysql/MysqlRoutinesIT.java
  src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesIT.java
  src/test/java/org/schemaspy/integrationtesting/mysql/MysqlSpacesNoDotsIT.java
  src/test/java/org/schemaspy/integrationtesting/mysql/MysqlXMLIT.java
  src/test/java/org/schemaspy/testcontainer/InformixIndexIT.java
  src/test/java/org/schemaspy/testcontainer/InformixIndexXMLIT.java
  src/test/java/org/schemaspy/testcontainer/MSSQLServerIT.java
  src/test/java/org/schemaspy/testcontainer/OracleIT.java
  src/test/java/org/schemaspy/testing/ExitCodeRule.java
Labels: bugfix

#338 336 show only selected database type
  src/main/java/org/schemaspy/Config.java
  src/main/java/org/schemaspy/db/config/PropertiesResolver.java
  src/main/java/org/schemaspy/util/ConnectionURLBuilder.java
  src/test/java/org/schemaspy/ConfigIT.java
  src/test/java/org/schemaspy/testing/ResettingOutputCapture.java
Labels: enhancement
